"""
Sales Prediction Dashboard
==========================

A simple web dashboard for the project. It shows the sales data, the model
comparison, and lets you enter order details to get a predicted sales amount.

Before running this, first run:   python src/model.py
(that creates the trained models this dashboard loads)

Then run:   streamlit run app.py
"""

import os

import joblib
import pandas as pd
import streamlit as st

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
RESULT_DIR = os.path.join(PROJECT_DIR, "outputs", "results")
GRAPH_DIR = os.path.join(PROJECT_DIR, "outputs", "graphs")

st.set_page_config(page_title="Sales Prediction Dashboard",
                   page_icon="📈", layout="wide")


# ---------------------------------------------------------------------------
# Load the trained models and the cleaned data
# ---------------------------------------------------------------------------
# @st.cache_data tells Streamlit to load these files only once instead of
# reloading them every time the user clicks something.
@st.cache_data
def load_everything():
    bundle = joblib.load(os.path.join(RESULT_DIR, "trained_models.pkl"))
    data = pd.read_csv(os.path.join(RESULT_DIR, "cleaned_sales.csv"),
                       parse_dates=["ORDERDATE"])
    return bundle, data


if not os.path.exists(os.path.join(RESULT_DIR, "trained_models.pkl")):
    st.error("Trained models not found. Please run `python src/model.py` first.")
    st.stop()

bundle, sales_data = load_everything()
models = bundle["models"]
results_table = bundle["results_table"]
best_model_name = bundle["best_model_name"]
options = bundle["options"]

st.title("📈 Sales Prediction Dashboard")
st.caption("Comparative Analysis of Sales Prediction Using Machine Learning Techniques")

# Four headline numbers at the top
best_row = results_table[results_table["Model"] == best_model_name].iloc[0]
col1, col2, col3, col4 = st.columns(4)
col1.metric("Total Orders", f"{len(sales_data):,}")
col2.metric("Total Sales", f"{sales_data['SALES'].sum():,.0f}")
col3.metric("Best Model", best_model_name)
col4.metric("Best R² Score", f"{best_row['R2']:.4f}")

tab1, tab2, tab3 = st.tabs(["📊 Sales Trends", "🏆 Model Comparison", "🔮 Predict Sales"])


# ---------------------------------------------------------------------------
# TAB 1 : Sales trends
# ---------------------------------------------------------------------------
with tab1:
    st.subheader("Monthly Sales Trend")
    monthly = sales_data.set_index("ORDERDATE")["SALES"].resample("ME").sum()
    st.line_chart(monthly)

    left, right = st.columns(2)

    with left:
        st.subheader("Sales by Product Category")
        category = (sales_data.groupby("PRODUCTLINE")["SALES"]
                    .sum().sort_values(ascending=False))
        st.bar_chart(category)

    with right:
        st.subheader("Top 10 Countries by Sales")
        country = (sales_data.groupby("COUNTRY")["SALES"]
                   .sum().sort_values(ascending=False).head(10))
        st.bar_chart(country)

    st.subheader("Sample of the Cleaned Dataset")
    st.dataframe(
        sales_data[["ORDERDATE", "PRODUCTLINE", "QUANTITYORDERED", "MSRP",
                    "COUNTRY", "TERRITORY", "SALES"]].head(20),
        width="stretch",
    )


# ---------------------------------------------------------------------------
# TAB 2 : Model comparison
# ---------------------------------------------------------------------------
with tab2:
    st.subheader("Comparison Table")
    st.dataframe(results_table, width="stretch", hide_index=True)
    st.success(f"Best performing model: **{best_model_name}** "
               f"(R² = {best_row['R2']}, RMSE = {best_row['RMSE']})")

    left, right = st.columns(2)
    with left:
        st.write("**R² Score — higher is better**")
        st.bar_chart(results_table.set_index("Model")["R2"])
    with right:
        st.write("**RMSE — lower is better**")
        st.bar_chart(results_table.set_index("Model")["RMSE"])

    st.subheader("Graphs Generated by the Project")
    graph_files = {
        "Actual vs Predicted Sales": "06_actual_vs_predicted.png",
        "Model Performance Comparison": "08_model_performance_comparison.png",
        "Random Forest Feature Importance": "09_random_forest_feature_importance.png",
        "Correlation Heatmap": "05_correlation_heatmap.png",
    }
    choice = st.selectbox("Choose a graph to view", list(graph_files.keys()))
    image_path = os.path.join(GRAPH_DIR, graph_files[choice])
    if os.path.exists(image_path):
        st.image(image_path, width="stretch")
    else:
        st.warning("Graph not found. Run `python src/model.py` to generate it.")


# ---------------------------------------------------------------------------
# TAB 3 : Make a prediction
# ---------------------------------------------------------------------------
with tab3:
    st.subheader("Enter Order Details to Predict Sales")
    st.write("Fill in the details of a new order and all three models will "
             "predict the sales amount.")

    left, middle, right = st.columns(3)
    with left:
        quantity = st.number_input("Quantity Ordered", min_value=1,
                                   max_value=200, value=35)
        msrp = st.number_input("MSRP (list price per unit)", min_value=1,
                               max_value=500, value=95)
    with middle:
        product_line = st.selectbox("Product Line", options["PRODUCTLINE"])
        country = st.selectbox("Country", options["COUNTRY"])
    with right:
        territory = st.selectbox("Territory", options["TERRITORY"])
        order_date = st.date_input("Order Date",
                                   value=pd.Timestamp("2005-05-15"))

    if st.button("Predict Sales", type="primary"):
        # Build a one-row table with exactly the same columns used in training.
        new_order = pd.DataFrame([{
            "QUANTITYORDERED": quantity,
            "MSRP": msrp,
            "ORDER_YEAR": order_date.year,
            "ORDER_MONTH": order_date.month,
            "ORDER_QUARTER": (order_date.month - 1) // 3 + 1,
            "ORDER_DAYOFWEEK": order_date.weekday(),
            "PRODUCTLINE": product_line,
            "COUNTRY": country,
            "TERRITORY": territory,
        }])

        # One-hot encode the text columns the same way as during training.
        encoded = pd.get_dummies(
            new_order, columns=bundle["categorical_features"], drop_first=True
        )
        # reindex adds any missing dummy columns as 0 and puts them in the
        # same order the models were trained on. This step is essential.
        encoded = encoded.reindex(columns=bundle["feature_columns"], fill_value=0)

        st.write("### Predicted Sales Amount")
        prediction_columns = st.columns(3)
        for column, (model_name, model) in zip(prediction_columns, models.items()):
            predicted_value = model.predict(encoded)[0]
            label = model_name
            if model_name == best_model_name:
                label = f"{model_name} ⭐ best"
            column.metric(label, f"{predicted_value:,.2f}")

        st.info(f"Trust the **{best_model_name}** number most — it had the "
                f"highest R² score on the test data.")
